---

- name: Download APT signing key
  ansible.builtin.get_url:
    url: "{{ docker[ansible_distribution]['gpg_key'] }}"
    dest: /tmp/docker.gpg
    validate_certs: false
    mode: "0644"
  environment:
    https_proxy: "{{ https_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
  check_mode: no

- name: Import APT signing key
  ansible.builtin.apt_key:
    file: /tmp/docker.gpg
    state: present

- name: Add Docker repository.
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.package:
    name: "{{ package }}"
    state: present
  loop: "{{ docker_packages }}"
  loop_control:
    loop_var: package
  become: yes

- name: Start Docker service
  ansible.builtin.service:
    name: Docker
    state: started
    enabled: yes
  become: yes

- name: Install pip modules
  ansible.builtin.pip:
    name: "{{ package }}"
  environment:
    https_proxy: "{{ https_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
  loop: "{{ docker_pip }}"
  loop_control:
    loop_var: package
  tags: molecule-idempotence-notest

- name: Add users to docker group
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: yes
  loop: "{{ docker_users | default([]) }}"
