---

- name: Download APT signing key
  ansible.builtin.get_url:
    url: "{{ docker[ansible_distribution]['gpg_key'] }}"
    dest: /tmp/docker.gpg
    validate_certs: false
    mode: "0644"
  environment:
    https_proxy: "{{ https_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
  check_mode: no

- name: Retrieve fingerprint from key
  ansible.builtin.shell: >-
    gpg --show-keys --with-colons /tmp/docker.gpg |
    grep -m1 "fpr:" |
    awk -F: '{print $10}'
  changed_when: false
  check_mode: no
  register: __gpg_fpr

- name: Delete APT signing key from legacy location
  ansible.builtin.apt_key:
    id: "0x{{ __gpg_fpr.stdout }}"
    state: absent
    keyring: /etc/apt/trusted.gpg

- name: Import APT signing key into the proper drop-in directory
  ansible.builtin.apt_key:
    file: /tmp/docker.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Delete obsolete repository file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/download_docker_com_linux_debian.list
    state: absent

- name: Setup repository definition
  ansible.builtin.apt_repository:
    filename: docker-ce
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.package:
    name: "{{ package }}"
    state: present
  loop: "{{ docker_packages }}"
  loop_control:
    loop_var: package
  become: yes

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Install pip modules
  ansible.builtin.pip:
    name: "{{ package }}"
  environment:
    https_proxy: "{{ https_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
  loop: "{{ docker_pip }}"
  loop_control:
    loop_var: package
  tags: molecule-idempotence-notest

- name: Add users to docker group
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | inspur.sm.user | sensu.sensu_go.user | theforeman.foreman.user
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: yes
  loop: "{{ docker_users | default([]) }}"
