---
#
# Install Docker CE

- name: Show OS specifics
  ansible.builtin.debug:
    msg:
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_os_family: {{ ansible_os_family }}"

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Define OS specific task files  # noqa var-naming
  ansible.builtin.set_fact:
    "{{ item }}": "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "tasks/{{ item | regex_replace('_', '-') }}"
  loop:
    - pre_install
    - install
    - config
    - post_config

- name: Pre-install phase
  ansible.builtin.include_tasks: "{{ pre_install }}"

- name: Install phase
  ansible.builtin.include_tasks: "{{ install }}"

- name: Config phase
  ansible.builtin.include_tasks: "{{ config }}"

- name: Post-config phase
  ansible.builtin.include_tasks: "{{ post_config }}"

- name: Scripts & tools
  ansible.builtin.include_tasks: scripts.yml
