---

- name: Copy scripts to make life easier
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: docker
    mode: "0550"
  loop:
    - docker-clean.sh
    - docker-compose-backup.sh
