---

# ---------------------------------------------------------
# Docker daemon config
# ---------------------------------------------------------

- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Read Docker daemon file
  command: cat /etc/docker/daemon.json
  register: docker_daemon_content
  changed_when: no
  failed_when: no
  check_mode: no

- name: Get current daemon settings + required API settings
  set_fact:
    docker_daemon: "{{ docker_daemon_content.stdout | from_json }}"
  when: docker_daemon_content.stdout|length > 0

- name: Merge existing and new settings
  set_fact:
    docker_daemon_options: "{{ docker_daemon | combine(docker_daemon_options) }}"


# ---------------------------------------------------------
# API
# ---------------------------------------------------------

- name: Define API settings
  block:

    - name: Show if API should use TLS
      debug:
        var: docker_api_tls

    - name: Get the required API settings
      set_fact:
        docker_daemon_api: "{{ docker_daemon_api_tls if docker_api_tls else docker_daemon_api_notls }}"

    - name: Merge existing and new settings
      set_fact:
        docker_daemon_options: "{{ docker_daemon_options | combine(docker_daemon_api) }}"

  when: docker_api|bool


# ---------------------------------------------------------
# daemon config
# ---------------------------------------------------------

- name: Docker daemon file
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_options | to_nice_json }}"
    mode: '0644'
  register: docker_daemon


# ---------------------------------------------------------
# Systemd
# ---------------------------------------------------------

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Configure API access over tcp
  become: yes
  template:
    src: "override.conf.j2"
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: '0644'
  register: docker_service

- name: Configure docker to use HTTP proxy
  copy:
    content: |
      [Service]
      Environment="HTTP_PROXY=http://{{ proxy_ip }}:{{ proxy_port }}/"
      Environment="HTTPS_PROXY=http://{{ proxy_ip }}:{{ proxy_port }}/"
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: "0644"
  when: docker_proxy_ip is defined and docker_proxy_port is defined
  register: docker_proxy

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Restart Docker when configuration changes
  service:
    name: docker
    state: restarted
  when: docker_daemon.changed|bool or docker_service.changed|bool or docker_proxy.changed|bool  # noqa no-handler



# Swarm
#
# - name: Init docker swarm mode
#   docker_swarm:
#     state: "{{ 'present' if docker_swarm|bool else 'absent' }}"
#     advertise_addr: "{{ docker_swarm_addr | default(ansible_enp0s8.ipv4.address) }}"


# ---------------------------------------------------------
# Networking
# ---------------------------------------------------------

- name: Configure networking
  block:

    - name: Populate service facts
      service_facts:

    - name: Activate IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        sysctl_file: /etc/sysctl.d/99-docker.conf
        state: present
        reload: yes
      when: ansible_facts.services['firewalld.service'] is defined

    - name: Enable firewalld forwarding
      command: >-
        firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -d 0.0.0.0/0 -j ACCEPT
      when: ansible_facts.services['firewalld.service'] is defined

    - name: Reload firewalld configuration
      command: firewall-cmd --reload
      changed_when: false
      when: ansible_facts.services['firewalld.service'] is defined

  when: docker_networking_outbound|bool
