---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: Vbox
platforms:
  - name: centos7
    box: generic/centos7
    memory: 512
    cpus: 1
  - name: centos8
    box: generic/centos8
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
