---

- name: Extend the list of firewall ports  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    docker_firewall_ports: "{{ docker_firewall_ports + [ docker_api_listen_port + '/tcp' ] }}"
  when: docker_api_listen_port is defined

- name: Open firewalld services
  ansible.posix.firewalld:
    service: "{{ service }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop: "{{ docker_firewall_services }}"
  loop_control:
    loop_var: service

- name: Open firewalld ports
  ansible.posix.firewalld:
    port: "{{ port }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop: "{{ docker_firewall_ports }}"
  loop_control:
    loop_var: port
