---

- name: Extend the list of firewall ports
  set_fact:
    docker_firewall_ports: "{{ docker_firewall_ports + [ docker_api_listen_port+'/tcp' ] }}"
  when: docker_api_listen_port is defined

- name: Open firewalld services
  firewalld:
    service: "{{ service }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop: "{{ docker_firewall_services }}"
  loop_control:
    loop_var: service

- name: Open firewalld ports
  firewalld:
    port: "{{ port }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop: "{{ docker_firewall_ports }}"
  loop_control:
    loop_var: port
