---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    docker_lvm: False
    docker_vg: dockervg
    docker_pv: /dev/sdb
    docker_root: /export/docker
    docker_lvm_setup: "{'vg': [{'name': '{{ docker_vg }}', 'pv': '{{ docker_pv }}'}], 'lv': [{'name': 'lv_docker', 'vg': '{{ docker_vg }}', 'size': '10G', 'mp': '/var/lib/docker', 'fstype': 'xfs'}, {'name': 'lv_docker_data', 'vg': '{{ docker_vg }}', 'size': '10G', 'mp': '{{ docker_root }}', 'fstype': 'xfs'}]}"
  tasks:
    - name: Include role 'ansible-role-docker'
      ansible.builtin.include_role:
        name: ansible-role-docker
