---

- name: Install prerequisites (RHEL7)  # noqa fqcn[action-core]
  ansible.builtin.yum:
    name: "{{ docker_packages_prereqs }}"
    state: present
  when: ansible_distribution_major_version | int == 7

- name: Install prerequisites (RHEL8+/Fedora)
  ansible.builtin.dnf:
    name: "{{ docker_packages_prereqs }}"
    state: present
  when: ansible_distribution_major_version | int >= 8

# - name: Get pip version
#   command: pip --version
#   changed_when: false
#   check_mode: no
#   register: pip
#
# - name: Upgrade pip if version > 19.0.0
#   command: pip install --upgrade pip
#   when: pip.stdout.split(' ')[1] is version('19.0.0', '<')
