---

- name: Fedora >= 31 requirements
  block:

    - name: Install grubby
      dnf:
        name: grubby
        state: present

    - name: Check if systemd.unified_cgroup_hierarchy=0 is set in kernelopts
      command: grep -Eq 'GRUB_CMDLINE_LINUX=.*systemd\.unified_cgroup_hierarchy=0' /etc/default/grub
      register: grubenv_has_cgroup_exception
      check_mode: no
      failed_when: no
      changed_when: no

    - name: Remove previously configured systemd.unified_cgroup_hierarchy=0 in kernelopts
      command: grubby --update-kernel=ALL --remove-args="systemd.unified_cgroup_hierarchy=0"
      when: grubenv_has_cgroup_exception.rc == 0

  when:
    - ansible_distribution == "Fedora"
