---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
#  - name: centos8
#    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
#    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
